#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'vmbuilder',
 'build_date': '2011-05-19 15:29:41 -0500',
 'clean': None,
 'date': '2011-05-18 18:07:40 -0500',
 'revision_id': 'serge.hallyn@canonical.com-20110518230740-mqez1k0sfhazxxf4',
 'revno': 466}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
